version: 2
jobs:
  build:
    docker:
      - image: node:8.0

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: "Checking Versions"
          command: |
            node --version
            npm --version

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: node --version

      - run: npm --version
      
      - run: yarn
      
      - run: ./strap -V

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
        
      - run: ./strap -V
      
      - run: cd samples/sample-datavault-react/

      - run: yarn 

      # TODO add solidity

      - store_test_results:
          path: reports


