version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8

    working_directory: ~/dapploy

    steps:
      - checkout

      - run:
          name: "Checking Versions"
          command: |
            node --version
            npm --version

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      
      - run:
          name: "Yarn project and samples"
          command: |
            yarn
            cd samples/sample-datavault-solidity
            yarn
            cd ../sample-datavault-react/
            yarn
            cd ../..

      - run: 
          name: "Run ganache-cli, test truffle, test dapploy"
          command: | 
            cd samples/sample-datavault-solidity
            node_modules/.bin/ganache-cli > /dev/null &
            sleep 5
            node_modules/.bin/truffle test
            cd ../..
            ./dapploy -sc .circleci/circle_dapploy.conf
  
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # TODO run some more tests
      - store_test_results:
          path: ~/dapploy/.circle/reports


